[package]
name = "wizi"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13"
iced_layershell = "0.13"
futures-util = "0.3.31"
tokio = { version = "1", features = ["full"] }
zbus = { version = "5.6.0", default-features = false, features = ["tokio"] }

